name: Backend Security

on:
  push:
    branches: [main, dev]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-security.yml'
  pull_request:
    branches: [main, dev]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-security.yml'

env:
  PYTHON_VERSION: "3.12"

jobs:
  security:
    name: Backend Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Install security tools
      run: |
        python -m pip install --upgrade pip
        pip install bandit safety
    
    - name: Run Bandit security scan
      working-directory: ./backend
      run: |
        bandit -r . -f json -o bandit-report.json || true
    
    - name: Run Safety dependency check
      working-directory: ./backend
      run: |
        safety check --json --output safety-report.json || true
    
    - name: Upload security reports
      uses: actions/upload-artifact@v4
      with:
        name: backend-security-reports
        path: |
          backend/bandit-report.json
          backend/safety-report.json 