name: Backend Tests

on:
  push:
    branches: [main, dev]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-test.yml'
  pull_request:
    branches: [main, dev]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-test.yml'

env:
  PYTHON_VERSION: "3.12"

jobs:
  test:
    name: Backend Tests & Coverage
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Install uv
      run: |
        python -m pip install --upgrade pip
        pip install uv
    
    - name: Install dependencies
      working-directory: ./backend
      run: |
        uv sync --extra dev
    
    - name: Run tests with coverage
      working-directory: ./backend
      run: |
        uv run pytest --cov=core --cov=tests --cov-report=xml --cov-report=term-missing
    
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: leandrofahur/ask-wise
        directory: ./backend 